#!/usr/bin/env python3
"""
Genvuln_report.py - Generic HTML Report Generator
This script provides a generic skeleton for parsing abstract JSON and XML datasets
and generating a formatted HTML table report using a referenced CSS style sheet.
"""

import os
import json
import xml.etree.ElementTree as ET

def parse_generic_json(file_path):
    """
    Parses a generic JSON list of objects.
    """
    parsed_items = []
    if not os.path.exists(file_path):
        print(f"[-] Warning: JSON file not found at {file_path}")
        return parsed_items
        
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            # Safe parsing of an expected list of structures
            if isinstance(data, list):
                for entry in data:
                    item = {
                        "id": entry.get("id", "N/A"),
                        "name": entry.get("name", "Unknown"),
                        "status": entry.get("status", "N/A"),
                        "details": entry.get("details", "None")
                    }
                    parsed_items.append(item)
            elif isinstance(data, dict):
                # Handle single dictionary if applicable
                parsed_items.append({
                    "id": data.get("id", "N/A"),
                    "name": data.get("name", "Unknown"),
                    "status": data.get("status", "N/A"),
                    "details": data.get("details", "None")
                })
    except json.JSONDecodeError as e:
        print(f"[-] Error parsing JSON file: {e}")
    return parsed_items


def parse_generic_xml(file_path):
    """
    Parses a generic XML tree structure.
    """
    parsed_items = []
    if not os.path.exists(file_path):
        print(f"[-] Warning: XML file not found at {file_path}")
        return parsed_items

    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        
        # Traverse elements generically
        for elem in root.findall('.//record'):
            item = {
                "name": elem.attrib.get("name", "Unknown"),
                "value": elem.text.strip() if elem.text else "N/A"
            }
            parsed_items.append(item)
    except ET.ParseError as e:
        print(f"[-] Error parsing XML file: {e}")
    return parsed_items


def build_html_report(json_records, xml_records, output_path, stylesheet_path="reference/global_report.css"):
    """
    Compiles parsed records into a clean HTML layout styled with the referenced CSS.
    """
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formatted Data Assessment Report</title>
    <link rel="stylesheet" href="{stylesheet_path}">
</head>
<body>
    <header class="report-header">
        <h1>Assessment & Integrity Report</h1>
        <p class="subtitle">Generated by Automated Compilation Tool</p>
    </header>
    
    <main class="report-container">
        <section class="report-section">
            <h2>Record Set A (Parsed JSON)</h2>
            <div class="table-container">
                <table class="report-table">
                    <thead>
                        <tr>
                            <th>Identifier</th>
                            <th>Reference Name</th>
                            <th>State / Status</th>
                            <th>Details</th>
                        </tr>
                    </thead>
                    <tbody>
"""

    if not json_records:
        html_content += """
                        <tr>
                            <td colspan="4" class="no-data">No active JSON records found or compiled.</td>
                        </tr>"""
    else:
        for record in json_records:
            html_content += f"""
                        <tr>
                            <td>{record['id']}</td>
                            <td>{record['name']}</td>
                            <td><span class="status-badge">{record['status']}</span></td>
                            <td>{record['details']}</td>
                        </tr>"""

    html_content += """
                    </tbody>
                </table>
            </div>
        </section>

        <section class="report-section">
            <h2>Record Set B (Parsed XML)</h2>
            <div class="table-container">
                <table class="report-table">
                    <thead>
                        <tr>
                            <th>Target Element</th>
                            <th>Assigned Value</th>
                        </tr>
                    </thead>
                    <tbody>
"""

    if not xml_records:
        html_content += """
                        <tr>
                            <td colspan="2" class="no-data">No active XML elements found or compiled.</td>
                        </tr>"""
    else:
        for record in xml_records:
            html_content += f"""
                        <tr>
                            <td><strong>{record['name']}</strong></td>
                            <td>{record['value']}</td>
                        </tr>"""

    html_content += """
                    </tbody>
                </table>
            </div>
        </section>
    </main>

    <footer class="report-footer">
        <p>End of Generated Report</p>
    </footer>
</body>
</html>
"""

    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        print(f"[+] Report compiled successfully: {output_path}")
    except OSError as e:
        print(f"[-] Error writing HTML report: {e}")


def main():
    # Setup placeholder target inputs for demonstration/testing
    json_source = "data_source.json"
    xml_source = "data_source.xml"
    output_html = "assessment_report.html"

    print("[*] Starting report compiler...")
    json_data = parse_generic_json(json_source)
    xml_data = parse_generic_xml(xml_source)

    build_html_report(json_data, xml_data, output_html)

if __name__ == "__main__":
    main()
